version: '3.7'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: contrigra/foodgram:latest
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.4
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
    restart: always

