# Generated by Django 3.1.4 on 2021-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients',
                                         through='api.RecipeIngredient',
                                         to='api.Ingredient',
                                         verbose_name='Ингредиенты'),
        ),
    ]
