# Generated by Django 3.1.4 on 2021-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20210318_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True,
                                         related_name='ingredients',
                                         through='api.RecipeIngredient',
                                         to='api.Ingredient',
                                         verbose_name='Ингредиенты'),
        ),
    ]
