# Generated by Django 3.1.4 on 2021-01-25 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210118_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='weight',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='value',
            field=models.PositiveSmallIntegerField(default=10, help_text='Добавьте необходимое количество ингредиентов', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ingredient weight'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
