# Generated by Django 3.1.4 on 2021-02-10 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20210125_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTag',
        ),
    ]
