# Generated by Django 3.1.4 on 2021-02-20 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20210220_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
