# Generated by Django 3.1.4 on 2021-02-25 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20210220_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favorites',
        ),
    ]
