# Generated by Django 3.1.4 on 2021-01-08 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201204_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['title'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=10, help_text='Add needed weight for the recipe', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ingredient weight'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredients', through='api.RecipeIngredient', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
