# Generated by Django 3.1.4 on 2021-01-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210115_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='api.TimeTag'),
        ),
    ]
